name: deploy project to staging server
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  deploy:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: pull code from github and rerun project on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ${{ secrets.PROJECT_PATH }} 
            git pull 
            yarn
            yarn build
            pm2 restart uadevs
